### ISSUE TITLE
New SRU Server for CERL's HPB

### ISSUE THREAD

**Issue by alexjahnke** [TomDeneire/ulpia#4]
The SRU server for CERL's HPB database has changed and is now: https://sru.k10plus.de/hpb
Sorry...

**Comment by TomDeneire** [comment]
Thanks for the message, I'll update the link!

**Comment by TomDeneire** [comment]
https://github.com/TomDeneire/ulpia/commit/cbf995103fc1eff9aa0724465e0d67bf70640fc8
